### ISSUE TITLE
Why should the sentence length be <= 40 characters? 

### ISSUE THREAD

**Issue by markfarrell** [dlwh/puck#1]
Hey, 

Could you clarify (on the README) why the sentence length must be <= 40 characters right now? 

What happens when sentences are ~100 characters in length?

**Comment by dlwh** [comment]
40 words, not 40 characters. 

Currently they're skipped and (()) is printed. You can set maxParseLength to whatever you want and it will work.

Parsing is cubic in the length of the sentence, so long sentences take a very long time.

**Comment by markfarrell** [comment]
I see, thanks for the clarification.

**Comment by dlwh** [comment]
one more thing: the vast majority of sentences in most text are length ≤40.
Like 95% for newspapers, more for general internet, perhaps somewhat less
for scientific papers.
