### ISSUE TITLE
Does it produce same output as Berkley Parser ?

### ISSUE THREAD

**Issue by kk00ss** [dlwh/puck#2]
Hello, I'm interested in using your library.
As It's (currently) designed for use with grammars trained with the Berkeley Parser - I assume Puck is a constituency parser.
Please confirm.

**Comment by dlwh** [comment]
It produces constituency parses. Usually they are identical to Berkeley
Parser parses, but there is sometimes a small amount of disagreement.

-- David

**Comment by kk00ss** [comment]
Thanks
