### ISSUE TITLE
It looks like puck depends on OpenCL and not CUDA, since you are reverencing javacl ?

### ISSUE THREAD

**Issue by kk00ss** [dlwh/puck#3]
please comment

**Comment by kk00ss** [comment]
I see you use CLContext which is specific for OpenCL.

**Comment by dlwh** [comment]
That's right. Though it's heavily optimized for Nvidia devices. It's known
to run on Intel's implementation, but not particularly well. (I originally
wanted to look at implementation for all three.

**Comment by kk00ss** [comment]
But guys with Radeons may be able to run it, so it would be better to inform them that it depends on OpenCL, but kernel itself is Nvidia optimized. I'm saying that because I bought new card for using it with Puck, and spent quite a lot of time configuring CUDA on Linux. Could you please change description.

**Comment by dlwh** [comment]
Fair enough.

**Comment by kk00ss** [comment]
It would be better description of a project if you substituted:
 It's (currently) designed for use with grammars trained with the Berkeley Parser and on NVIDIA cards.
with:
 It's (currently) designed for use with grammars trained with the Berkeley Parser, OpenCL API, but kernel was optimized for NVIDIA cards.

Original is confusing, people who can start using Puck with their iGPUs see it and think they need to buy NVIDIA GPU. Thanks

**Comment by dlwh** [comment]
i suppose. but it's likely to be no faster than the normal Berkeley Parser
under those circumstances
