### ISSUE TITLE
Unable to download prebuilt puck jar

### ISSUE THREAD

**Issue by kk00ss** [dlwh/puck#4]
[URL](http://www.scalanlp.org/releases/puck-assembly-0.2.jar)  is incorrect
However I see there is a file [URL](http://www.scalanlp.org/releases/puck-assembly-0.1.jar)

Thanks.

**Comment by dlwh** [comment]
http://www.scalanlp.org/releases/puck-assembly-0.1.jar

**Comment by kk00ss** [comment]
Thank you, I'm already testing it. Is there a way to obtain 0.2. jar file ?

**Comment by dlwh** [comment]
um, I think i have a bundled jar at home. I'll get back to you tonight. I
also can't build it now thanks to the issues in building javacl.

**Comment by dlwh** [comment]
actually, could you set the javacl version to 1.0-RC4? that might let you
build

**Comment by kk00ss** [comment]
I'm new to SBT, but the error happens when fetching parent-parent package named nativelibs4java-parent which has only one version - 1.10-SNAPSHOT.
Corresponding folder is https://oss.sonatype.org/content/repositories/snapshots/com/nativelibs4java/nativelibs4java-parent/ .
It does contain pom file which is downloaded and converted to ivy, but for some reason SBT says it doesn't see anything. Considering that every javacl version will have same parent-parent package (javacl - has parent - javacl-parent, which have parent nativelibs4java )- changing version is not going to help (I've checked that anyway already)

It looks like it's entirely SBT issue, I'm closing this issue.

**Comment by dlwh** [comment]
i uploaded a 0.2 assembly jar
